#!/bin/sh

# Resource Impl: http://concourse.ci/implementing-resources.html#out:-update-a-resource.
set -ex

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 </full/path/to/dir>"
  exit 1
fi
#######################################

# disable trace since we're interacting with sensitive values
set +x

eval "$(jq -r '.source | [
  "bucket=\(.bucket | @sh)",
  "path=\(.path // "" | @sh)",
  "change_dir_to=\(.change_dir_to // "." | @sh)",
  "AWS_ACCESS_KEY_ID=\(.access_key_id // "" | @sh)",
  "AWS_SECRET_ACCESS_KEY=\(.secret_access_key // "" | @sh)",
  "AWS_DEFAULT_REGION=\(.region // "" | @sh)",
  "options=\(.options // [] | join(" ") | @sh)"
] | join("\n")')"

# hints for static checking
: "${bucket:=}" "${path:=}" "${change_dir_to:=}" "${options:=}" "${AWS_ACCESS_KEY_ID:=}" "${AWS_SECRET_ACCESS_KEY:=}" "${AWS_DEFAULT_REGION:=}"

# Due to precedence rules, must be unset to support AWS IAM Roles.
if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
  export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
fi

# re-enable trace since we're done interacting with sensitive values
set -x

# Export AWS_DEFAULT_REGION if set
[ -n "$AWS_DEFAULT_REGION" ] && export AWS_DEFAULT_REGION

cd "${source}/${change_dir_to}"

echo "Uploading to S3..."
eval "set -- $options"
aws s3 sync . "s3://$bucket/$path" "$@"
echo "...done."

. "$(dirname "$0")/emit.sh" >&3
