#!/bin/sh

# Resource Impl: http://concourse.ci/implementing-resources.html#out:-update-a-resource.
set -ex

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 </full/path/to/dir>"
  exit 1
fi
#######################################

# disable trace since we're interacting with sensitive values
set +x

payload=$(cat)
bucket=$(printf '%s\n' "$payload" | jq -r '.source.bucket // ""')
path=$(printf '%s\n' "$payload" | jq -r '.source.path // ""')
change_dir_to=$(printf '%s\n' "$payload" | jq -r '.source.change_dir_to // ""')
options=$(printf '%s\n' "$payload" | jq -r '.source.options // [] | join(" ")')
AWS_ACCESS_KEY_ID=$(printf '%s\n' "$payload" | jq -r '.source.access_key_id // ""')
AWS_SECRET_ACCESS_KEY=$(printf '%s\n' "$payload" | jq -r '.source.secret_access_key // ""')
AWS_DEFAULT_REGION=$(printf '%s\n' "$payload" | jq -r '.source.region // ""')

# Due to precedence rules, must be unset to support AWS IAM Roles.
if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
  export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
fi

# re-enable trace since we're done interacting with sensitive values
set -x

# Export AWS_DEFAULT_REGION if set
[ -n "$AWS_DEFAULT_REGION" ] && export AWS_DEFAULT_REGION

cd "${source}/${change_dir_to}"

echo "Uploading to S3..."
eval "set -- $options"
aws s3 sync . "s3://$bucket/$path" "$@"
echo "...done."

. "$(dirname "$0")/emit.sh" >&3
